version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lotacao_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

  minio:
    image: minio/minio
    container_name: minio_storage
    environment:
      MINIO_ROOT_USER: "myaccesskey123"
      MINIO_ROOT_PASSWORD: "mysecretkey123"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - app_network

  app:
    build: .
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/lotacao_db"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      MINIO_ACCESS_KEY: "myaccesskey123"
      MINIO_SECRET_KEY: "My$ecureP@ssw0rd"
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres-data:
  minio-data:
