spring:
  application:
    name: projeto-pratico-implementacao-back-end
  datasource:
    url: jdbc:postgresql://localhost:5432/lotacao_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 300000 # 5 MINUTOS
    refresh-expiration-time: 3600000  # 1 HORA