spring:
  application:
    name: projeto-pratico-implementacao-back-end
  datasource:
    url: jdbc:postgresql://localhost:5432/lotacao_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true